# Generated by Django 2.2.16 on 2021-12-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
        ),
    ]
